# Generated by Django 5.0.7 on 2024-08-30 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=5000)),
                ('phone_number', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=500)),
                ('father_phone_number', models.CharField(max_length=500)),
                ('sslc_marks', models.FloatField()),
                ('high_school_name', models.CharField(max_length=500)),
                ('high_school_passing_year', models.CharField(max_length=100)),
                ('puc_marks', models.FloatField()),
                ('college_name', models.CharField(max_length=500)),
                ('college_passing_year', models.CharField(max_length=100)),
                ('year_of_enrollment', models.IntegerField()),
                ('year_of_passing', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubjectDetail',
            fields=[
                ('subject_code', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('sem', models.IntegerField(default=1)),
                ('subject_name', models.CharField(max_length=500)),
                ('schema', models.IntegerField()),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=500)),
                ('branch', models.CharField(max_length=200)),
                ('schema', models.IntegerField()),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form.studentdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField(default=1)),
                ('ia_1', models.IntegerField()),
                ('ia_2', models.IntegerField()),
                ('ia_3', models.IntegerField()),
                ('average_ia', models.FloatField(blank=True, null=True)),
                ('assignment_1', models.IntegerField()),
                ('assignment_2', models.IntegerField()),
                ('project_marks', models.IntegerField()),
                ('total_internal_marks', models.FloatField(blank=True, null=True)),
                ('external_marks', models.IntegerField()),
                ('total_marks', models.FloatField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('grade_point', models.FloatField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.subjectdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField(default=1)),
                ('ia_1', models.IntegerField()),
                ('ia_2', models.IntegerField()),
                ('ia_3', models.IntegerField()),
                ('average_ia', models.FloatField(blank=True, null=True)),
                ('assignment_1', models.IntegerField()),
                ('assignment_2', models.IntegerField()),
                ('project_marks', models.IntegerField()),
                ('total_internal_marks', models.FloatField(blank=True, null=True)),
                ('external_marks', models.IntegerField()),
                ('total_marks', models.FloatField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('grade_point', models.FloatField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.subjectdetail')),
            ],
        ),
    ]
